---
abstract: 'Monitoring Web Interface'
author:
  - 'Sven Nierlein, 2009-present, <sven@nierlein.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: gpl3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Thruk
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Inspector: 0
  DBD::mysql: 0
  DBI: 0
  Date::Calc: 6.3
  Date::Manip: 0
  DateTime: 0
  DateTime::TimeZone: 0
  Devel::Cycle: 0
  Excel::Template: 0
  FCGI: 0
  File::BOM: 0
  File::Slurp: 0
  GD: 2.44
  HTML::Entities: 0
  HTML::Escape: 0
  HTML::Lint: 0
  HTTP::Request: 0
  HTTP::Response: 0
  IO::String: 0
  JSON::XS: 0
  LWP::Protocol::connect: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Log::Dispatch::File: 0
  Log::Log4perl: 1.34
  MIME::Lite: 0
  Module::Load: 0
  Net::HTTP: 6.02
  Perl::Critic::Policy::Dynamic::NoIndirect: 0
  Perl::Critic::Policy::Modules::ProhibitPOSIXimport: 0
  Perl::Critic::Policy::NamingConventions::ProhibitMixedCaseSubs: 0
  Perl::Critic::Policy::ValuesAndExpressions::ProhibitAccessOfPrivateData: 0
  Plack: 1
  Socket: 0
  Storable: 0
  Template: 0
  Test::Cmd: 0
  Test::JavaScript: 0
  Test::Perl::Critic: 0
  Test::Pod: '1.4'
  Test::Pod::Coverage: 0
  Test::Simple: 0
  Test::Vars: 0
  Thread::Queue: 0
  Time::HiRes: 0
  URI::Escape: 0
  WWW::Mechanize::Firefox: 0
  parent: 0
  perl: 5.8.0
  threads: 0
resources:
  bugtracker: http://github.com/sni/Thruk/issues
  homepage: http://www.thruk.org
  license: http://opensource.org/licenses/gpl-3.0.html
  repository: http://github.com/sni/Thruk
version: '2.00'
